[package]
name = "p2p"
version = "0.1.0"
edition = "2024"
resolver = "3"


[dependencies]
ed25519-dalek = { version = "1.0", features = ["std", "serde"] }
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1"
tokio = { version = "1", features = ["full"] }

